/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdmitApprovBarChart: typeof import('./components/AdmitApprovBarChart.vue')['default']
    AverageProcessTimeChart: typeof import('./components/AverageProcessTimeChart.vue')['default']
    InvestmentBarChart: typeof import('./components/InvestmentBarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
